name: journey_gennie
description: "A new Flutter project."

publish_to: 'none' # This line prevents the package from being published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0" # Ensure compatibility with Dart SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Cupertino icons for iOS
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image.png
    - assets/logo.png
    - assets/home.png
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png

  # Fonts section (commented out but ready to use)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
